stages:
  - deploy

# --exclude-glob: exclude from deletion remote dir (es. logs, uploaded files, etc)
deploy:
  stage: deploy
  only:
    - master
  image: alpine:3.10
  variables:
    HOST: $FTP_HOST
    USERNAME: $FTP_USERNAME
    PASSWORD: $FTP_PASSWORD
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -e "
      set ftp:ssl-allow no;
      mirror --reverse --delete --verbose --use-cache --no-symlinks
      --parallel=5
      --exclude-glob .env
      --exclude-glob storage/logs/*.log
      repository-dir/ remote-dir/; quit;
      " -u $USERNAME,$PASSWORD $HOST